# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import stock_provider_pb2 as stock__provider__pb2


class StockStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/stock_api.Stock/SayHello',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetDayData = channel.unary_unary(
                '/stock_api.Stock/GetDayData',
                request_serializer=stock__provider__pb2.StockQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosDayDatas.FromString,
                )
        self.GetMinuteData = channel.unary_unary(
                '/stock_api.Stock/GetMinuteData',
                request_serializer=stock__provider__pb2.StockQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosDayDatas.FromString,
                )
        self.GetTodayMinuteData = channel.unary_unary(
                '/stock_api.Stock/GetTodayMinuteData',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosDayDatas.FromString,
                )
        self.GetPastMinuteData = channel.unary_unary(
                '/stock_api.Stock/GetPastMinuteData',
                request_serializer=stock__provider__pb2.PastMinuteQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosDayDatas.FromString,
                )
        self.GetSubscribeCodes = channel.unary_unary(
                '/stock_api.Stock/GetSubscribeCodes',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.GetBalance = channel.unary_unary(
                '/stock_api.Stock/GetBalance',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.Balance.FromString,
                )
        self.OrderStock = channel.unary_unary(
                '/stock_api.Stock/OrderStock',
                request_serializer=stock__provider__pb2.OrderMsg.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosOrderReturn.FromString,
                )
        self.ChangeOrder = channel.unary_unary(
                '/stock_api.Stock/ChangeOrder',
                request_serializer=stock__provider__pb2.OrderMsg.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosOrderReturn.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/stock_api.Stock/CancelOrder',
                request_serializer=stock__provider__pb2.OrderMsg.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosOrderReturn.FromString,
                )
        self.GetYearHigh = channel.unary_unary(
                '/stock_api.Stock/GetYearHigh',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.YearHighInfo.FromString,
                )
        self.RequestCybosTickData = channel.unary_unary(
                '/stock_api.Stock/RequestCybosTickData',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RequestCybosBidAsk = channel.unary_unary(
                '/stock_api.Stock/RequestCybosBidAsk',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RequestCybosSubject = channel.unary_unary(
                '/stock_api.Stock/RequestCybosSubject',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RequestCybosAlarm = channel.unary_unary(
                '/stock_api.Stock/RequestCybosAlarm',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RequestToTrader = channel.unary_unary(
                '/stock_api.Stock/RequestToTrader',
                request_serializer=stock__provider__pb2.TradeMsg.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RequestCybosTradeResult = channel.unary_unary(
                '/stock_api.Stock/RequestCybosTradeResult',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ReportOrderResult = channel.unary_unary(
                '/stock_api.Stock/ReportOrderResult',
                request_serializer=stock__provider__pb2.OrderResult.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.IsKospi = channel.unary_unary(
                '/stock_api.Stock/IsKospi',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.Bool.FromString,
                )
        self.SetViPriceInfo = channel.unary_unary(
                '/stock_api.Stock/SetViPriceInfo',
                request_serializer=stock__provider__pb2.ViPriceInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetViPrice = channel.unary_unary(
                '/stock_api.Stock/GetViPrice',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.Prices.FromString,
                )
        self.ListenTraderMsg = channel.unary_stream(
                '/stock_api.Stock/ListenTraderMsg',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.TradeMsg.FromString,
                )
        self.ListenCybosOrderResult = channel.unary_stream(
                '/stock_api.Stock/ListenCybosOrderResult',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosOrderResult.FromString,
                )
        self.ListenOrderResult = channel.unary_stream(
                '/stock_api.Stock/ListenOrderResult',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.OrderResult.FromString,
                )
        self.SetCurrentStock = channel.unary_unary(
                '/stock_api.Stock/SetCurrentStock',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetCurrentDateTime = channel.unary_unary(
                '/stock_api.Stock/SetCurrentDateTime',
                request_serializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetCompanyName = channel.unary_unary(
                '/stock_api.Stock/GetCompanyName',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.CompanyName.FromString,
                )
        self.GetFavoriteList = channel.unary_unary(
                '/stock_api.Stock/GetFavoriteList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.AddFavorite = channel.unary_unary(
                '/stock_api.Stock/AddFavorite',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveFavorite = channel.unary_unary(
                '/stock_api.Stock/RemoveFavorite',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ClearRecentList = channel.unary_unary(
                '/stock_api.Stock/ClearRecentList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetYesterdayTopAmountList = channel.unary_unary(
                '/stock_api.Stock/GetYesterdayTopAmountList',
                request_serializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
                response_deserializer=stock__provider__pb2.TopList.FromString,
                )
        self.GetYesterdayUpperLimitList = channel.unary_unary(
                '/stock_api.Stock/GetYesterdayUpperLimitList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.SetTodayAmountRatioList = channel.unary_unary(
                '/stock_api.Stock/SetTodayAmountRatioList',
                request_serializer=stock__provider__pb2.CodeList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetTodayAmountMomentumList = channel.unary_unary(
                '/stock_api.Stock/SetTodayAmountMomentumList',
                request_serializer=stock__provider__pb2.CodeList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetTodayAmountTopList = channel.unary_unary(
                '/stock_api.Stock/SetTodayAmountTopList',
                request_serializer=stock__provider__pb2.CodeList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBrokerSummary = channel.unary_unary(
                '/stock_api.Stock/GetBrokerSummary',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.BrokerSummary.FromString,
                )
        self.SetBrokerSummary = channel.unary_unary(
                '/stock_api.Stock/SetBrokerSummary',
                request_serializer=stock__provider__pb2.BrokerSummary.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AddBrokerMinuteTick = channel.unary_unary(
                '/stock_api.Stock/AddBrokerMinuteTick',
                request_serializer=stock__provider__pb2.BrokerMinuteTick.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBrokerMinuteTick = channel.unary_unary(
                '/stock_api.Stock/GetBrokerMinuteTick',
                request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
                response_deserializer=stock__provider__pb2.BrokerMinuteTickList.FromString,
                )
        self.GetTodayTopAmountList = channel.unary_unary(
                '/stock_api.Stock/GetTodayTopAmountList',
                request_serializer=stock__provider__pb2.TodayTopOption.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.GetRecentSearch = channel.unary_unary(
                '/stock_api.Stock/GetRecentSearch',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.GetViList = channel.unary_unary(
                '/stock_api.Stock/GetViList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.GetStrategyList = channel.unary_unary(
                '/stock_api.Stock/GetStrategyList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CodeList.FromString,
                )
        self.SetStrategyList = channel.unary_unary(
                '/stock_api.Stock/SetStrategyList',
                request_serializer=stock__provider__pb2.CodeList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListenCurrentStock = channel.unary_stream(
                '/stock_api.Stock/ListenCurrentStock',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                )
        self.ListenListChanged = channel.unary_stream(
                '/stock_api.Stock/ListenListChanged',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.ListType.FromString,
                )
        self.ListenBrokerSummary = channel.unary_stream(
                '/stock_api.Stock/ListenBrokerSummary',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.BrokerSummary.FromString,
                )
        self.ListenBrokerMinuteTick = channel.unary_stream(
                '/stock_api.Stock/ListenBrokerMinuteTick',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.BrokerMinuteTick.FromString,
                )
        self.ListenCybosTickData = channel.unary_stream(
                '/stock_api.Stock/ListenCybosTickData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosTickData.FromString,
                )
        self.ListenCybosBidAsk = channel.unary_stream(
                '/stock_api.Stock/ListenCybosBidAsk',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosBidAskTickData.FromString,
                )
        self.ListenCurrentTime = channel.unary_stream(
                '/stock_api.Stock/ListenCurrentTime',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
                )
        self.ListenCybosSubject = channel.unary_stream(
                '/stock_api.Stock/ListenCybosSubject',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosSubjectTickData.FromString,
                )
        self.ListenCybosAlarm = channel.unary_stream(
                '/stock_api.Stock/ListenCybosAlarm',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.CybosStockAlarm.FromString,
                )
        self.ListenSimulationStatusChanged = channel.unary_stream(
                '/stock_api.Stock/ListenSimulationStatusChanged',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.SimulationStatus.FromString,
                )
        self.SimulationData = channel.stream_stream(
                '/stock_api.Stock/SimulationData',
                request_serializer=stock__provider__pb2.SimulationMsg.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListenSimulationOperation = channel.unary_stream(
                '/stock_api.Stock/ListenSimulationOperation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.SimulationOperation.FromString,
                )
        self.StartSimulation = channel.unary_unary(
                '/stock_api.Stock/StartSimulation',
                request_serializer=stock__provider__pb2.SimulationOperation.SerializeToString,
                response_deserializer=stock__provider__pb2.Bool.FromString,
                )
        self.StopSimulation = channel.unary_unary(
                '/stock_api.Stock/StopSimulation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetSimulationStatus = channel.unary_unary(
                '/stock_api.Stock/SetSimulationStatus',
                request_serializer=stock__provider__pb2.SimulationStatus.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetSimulationStatus = channel.unary_unary(
                '/stock_api.Stock/GetSimulationStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stock__provider__pb2.SimulationStatus.FromString,
                )


class StockServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDayData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMinuteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodayMinuteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPastMinuteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubscribeCodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYearHigh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCybosTickData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCybosBidAsk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCybosSubject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCybosAlarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestToTrader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCybosTradeResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportOrderResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsKospi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetViPriceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetViPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenTraderMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCybosOrderResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenOrderResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCurrentStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCurrentDateTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompanyName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFavoriteList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFavorite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFavorite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearRecentList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYesterdayTopAmountList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYesterdayUpperLimitList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTodayAmountRatioList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTodayAmountMomentumList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTodayAmountTopList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrokerSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBrokerSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBrokerMinuteTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrokerMinuteTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodayTopAmountList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetViList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStrategyList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCurrentStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenListChanged(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenBrokerSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenBrokerMinuteTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCybosTickData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCybosBidAsk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCurrentTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCybosSubject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCybosAlarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenSimulationStatusChanged(self, request, context):
        """Simulation RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulationData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenSimulationOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSimulationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDayData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDayData,
                    request_deserializer=stock__provider__pb2.StockQuery.FromString,
                    response_serializer=stock__provider__pb2.CybosDayDatas.SerializeToString,
            ),
            'GetMinuteData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinuteData,
                    request_deserializer=stock__provider__pb2.StockQuery.FromString,
                    response_serializer=stock__provider__pb2.CybosDayDatas.SerializeToString,
            ),
            'GetTodayMinuteData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodayMinuteData,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.CybosDayDatas.SerializeToString,
            ),
            'GetPastMinuteData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPastMinuteData,
                    request_deserializer=stock__provider__pb2.PastMinuteQuery.FromString,
                    response_serializer=stock__provider__pb2.CybosDayDatas.SerializeToString,
            ),
            'GetSubscribeCodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscribeCodes,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.Balance.SerializeToString,
            ),
            'OrderStock': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderStock,
                    request_deserializer=stock__provider__pb2.OrderMsg.FromString,
                    response_serializer=stock__provider__pb2.CybosOrderReturn.SerializeToString,
            ),
            'ChangeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeOrder,
                    request_deserializer=stock__provider__pb2.OrderMsg.FromString,
                    response_serializer=stock__provider__pb2.CybosOrderReturn.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=stock__provider__pb2.OrderMsg.FromString,
                    response_serializer=stock__provider__pb2.CybosOrderReturn.SerializeToString,
            ),
            'GetYearHigh': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYearHigh,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.YearHighInfo.SerializeToString,
            ),
            'RequestCybosTickData': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCybosTickData,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestCybosBidAsk': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCybosBidAsk,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestCybosSubject': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCybosSubject,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestCybosAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCybosAlarm,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestToTrader': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestToTrader,
                    request_deserializer=stock__provider__pb2.TradeMsg.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestCybosTradeResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCybosTradeResult,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReportOrderResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOrderResult,
                    request_deserializer=stock__provider__pb2.OrderResult.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'IsKospi': grpc.unary_unary_rpc_method_handler(
                    servicer.IsKospi,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.Bool.SerializeToString,
            ),
            'SetViPriceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetViPriceInfo,
                    request_deserializer=stock__provider__pb2.ViPriceInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetViPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViPrice,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.Prices.SerializeToString,
            ),
            'ListenTraderMsg': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenTraderMsg,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.TradeMsg.SerializeToString,
            ),
            'ListenCybosOrderResult': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCybosOrderResult,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CybosOrderResult.SerializeToString,
            ),
            'ListenOrderResult': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenOrderResult,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.OrderResult.SerializeToString,
            ),
            'SetCurrentStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCurrentStock,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetCurrentDateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCurrentDateTime,
                    request_deserializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCompanyName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompanyName,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.CompanyName.SerializeToString,
            ),
            'GetFavoriteList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFavoriteList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'AddFavorite': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFavorite,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveFavorite': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFavorite,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ClearRecentList': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearRecentList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetYesterdayTopAmountList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYesterdayTopAmountList,
                    request_deserializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
                    response_serializer=stock__provider__pb2.TopList.SerializeToString,
            ),
            'GetYesterdayUpperLimitList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYesterdayUpperLimitList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'SetTodayAmountRatioList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTodayAmountRatioList,
                    request_deserializer=stock__provider__pb2.CodeList.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetTodayAmountMomentumList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTodayAmountMomentumList,
                    request_deserializer=stock__provider__pb2.CodeList.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetTodayAmountTopList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTodayAmountTopList,
                    request_deserializer=stock__provider__pb2.CodeList.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBrokerSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrokerSummary,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.BrokerSummary.SerializeToString,
            ),
            'SetBrokerSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBrokerSummary,
                    request_deserializer=stock__provider__pb2.BrokerSummary.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddBrokerMinuteTick': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBrokerMinuteTick,
                    request_deserializer=stock__provider__pb2.BrokerMinuteTick.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBrokerMinuteTick': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrokerMinuteTick,
                    request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
                    response_serializer=stock__provider__pb2.BrokerMinuteTickList.SerializeToString,
            ),
            'GetTodayTopAmountList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodayTopAmountList,
                    request_deserializer=stock__provider__pb2.TodayTopOption.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'GetRecentSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentSearch,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'GetViList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'GetStrategyList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategyList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CodeList.SerializeToString,
            ),
            'SetStrategyList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStrategyList,
                    request_deserializer=stock__provider__pb2.CodeList.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListenCurrentStock': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCurrentStock,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
            ),
            'ListenListChanged': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenListChanged,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.ListType.SerializeToString,
            ),
            'ListenBrokerSummary': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenBrokerSummary,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.BrokerSummary.SerializeToString,
            ),
            'ListenBrokerMinuteTick': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenBrokerMinuteTick,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.BrokerMinuteTick.SerializeToString,
            ),
            'ListenCybosTickData': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCybosTickData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CybosTickData.SerializeToString,
            ),
            'ListenCybosBidAsk': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCybosBidAsk,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CybosBidAskTickData.SerializeToString,
            ),
            'ListenCurrentTime': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCurrentTime,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
            ),
            'ListenCybosSubject': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCybosSubject,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CybosSubjectTickData.SerializeToString,
            ),
            'ListenCybosAlarm': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCybosAlarm,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.CybosStockAlarm.SerializeToString,
            ),
            'ListenSimulationStatusChanged': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenSimulationStatusChanged,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.SimulationStatus.SerializeToString,
            ),
            'SimulationData': grpc.stream_stream_rpc_method_handler(
                    servicer.SimulationData,
                    request_deserializer=stock__provider__pb2.SimulationMsg.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListenSimulationOperation': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenSimulationOperation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.SimulationOperation.SerializeToString,
            ),
            'StartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSimulation,
                    request_deserializer=stock__provider__pb2.SimulationOperation.FromString,
                    response_serializer=stock__provider__pb2.Bool.SerializeToString,
            ),
            'StopSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetSimulationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSimulationStatus,
                    request_deserializer=stock__provider__pb2.SimulationStatus.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSimulationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stock__provider__pb2.SimulationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stock_api.Stock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stock(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SayHello',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDayData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetDayData',
            stock__provider__pb2.StockQuery.SerializeToString,
            stock__provider__pb2.CybosDayDatas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMinuteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetMinuteData',
            stock__provider__pb2.StockQuery.SerializeToString,
            stock__provider__pb2.CybosDayDatas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTodayMinuteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetTodayMinuteData',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.CybosDayDatas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPastMinuteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetPastMinuteData',
            stock__provider__pb2.PastMinuteQuery.SerializeToString,
            stock__provider__pb2.CybosDayDatas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubscribeCodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetSubscribeCodes',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetBalance',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.Balance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OrderStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/OrderStock',
            stock__provider__pb2.OrderMsg.SerializeToString,
            stock__provider__pb2.CybosOrderReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/ChangeOrder',
            stock__provider__pb2.OrderMsg.SerializeToString,
            stock__provider__pb2.CybosOrderReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/CancelOrder',
            stock__provider__pb2.OrderMsg.SerializeToString,
            stock__provider__pb2.CybosOrderReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetYearHigh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetYearHigh',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.YearHighInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestCybosTickData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RequestCybosTickData',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestCybosBidAsk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RequestCybosBidAsk',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestCybosSubject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RequestCybosSubject',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestCybosAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RequestCybosAlarm',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestToTrader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RequestToTrader',
            stock__provider__pb2.TradeMsg.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestCybosTradeResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RequestCybosTradeResult',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportOrderResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/ReportOrderResult',
            stock__provider__pb2.OrderResult.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsKospi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/IsKospi',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.Bool.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetViPriceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetViPriceInfo',
            stock__provider__pb2.ViPriceInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetViPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetViPrice',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.Prices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenTraderMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenTraderMsg',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.TradeMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCybosOrderResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCybosOrderResult',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CybosOrderResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenOrderResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenOrderResult',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.OrderResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCurrentStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetCurrentStock',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCurrentDateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetCurrentDateTime',
            google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCompanyName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetCompanyName',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.CompanyName.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFavoriteList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetFavoriteList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFavorite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/AddFavorite',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFavorite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/RemoveFavorite',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearRecentList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/ClearRecentList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetYesterdayTopAmountList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetYesterdayTopAmountList',
            google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
            stock__provider__pb2.TopList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetYesterdayUpperLimitList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetYesterdayUpperLimitList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTodayAmountRatioList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetTodayAmountRatioList',
            stock__provider__pb2.CodeList.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTodayAmountMomentumList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetTodayAmountMomentumList',
            stock__provider__pb2.CodeList.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTodayAmountTopList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetTodayAmountTopList',
            stock__provider__pb2.CodeList.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBrokerSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetBrokerSummary',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.BrokerSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetBrokerSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetBrokerSummary',
            stock__provider__pb2.BrokerSummary.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBrokerMinuteTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/AddBrokerMinuteTick',
            stock__provider__pb2.BrokerMinuteTick.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBrokerMinuteTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetBrokerMinuteTick',
            stock__provider__pb2.StockCodeQuery.SerializeToString,
            stock__provider__pb2.BrokerMinuteTickList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTodayTopAmountList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetTodayTopAmountList',
            stock__provider__pb2.TodayTopOption.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecentSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetRecentSearch',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetViList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetViList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStrategyList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetStrategyList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStrategyList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetStrategyList',
            stock__provider__pb2.CodeList.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCurrentStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCurrentStock',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.StockCodeQuery.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenListChanged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenListChanged',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.ListType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenBrokerSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenBrokerSummary',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.BrokerSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenBrokerMinuteTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenBrokerMinuteTick',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.BrokerMinuteTick.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCybosTickData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCybosTickData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CybosTickData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCybosBidAsk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCybosBidAsk',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CybosBidAskTickData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCurrentTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCurrentTime',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCybosSubject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCybosSubject',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CybosSubjectTickData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenCybosAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenCybosAlarm',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.CybosStockAlarm.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenSimulationStatusChanged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenSimulationStatusChanged',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.SimulationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimulationData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/stock_api.Stock/SimulationData',
            stock__provider__pb2.SimulationMsg.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenSimulationOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock_api.Stock/ListenSimulationOperation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.SimulationOperation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/StartSimulation',
            stock__provider__pb2.SimulationOperation.SerializeToString,
            stock__provider__pb2.Bool.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/StopSimulation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSimulationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/SetSimulationStatus',
            stock__provider__pb2.SimulationStatus.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock_api.Stock/GetSimulationStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stock__provider__pb2.SimulationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
